---
apiVersion: v1
kind: Pod
metadata:
  name: navapp
  labels:
    app: openrouteservice
    env: dev
spec:
  containers:
    - name: navapp
      image: openrouteservice/openrouteservice:latest
      imagePullPolicy: Always
      ports:
        - name: api
          containerPort: 8080
          protocol: TCP
    volumeMounts:
    - name: navapp
      mountPath: /openrouteservice/src/main/files
  volumes:
  - name: navapp
    persistentVolumeClaim:
      claimName: navapp-claim
