apiVersion: v1
kind: PersistentVolume
metadata:
  name: navapp
  labels:
    app: openrouteservice
    env: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - Read
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-csi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxxxxx